# Generated by Django 4.2.6 on 2023-12-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('osu_flag', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
        ),
    ]
