# Generated by Django 4.2.6 on 2023-10-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('discord_user_id', models.CharField(blank=True, max_length=20)),
                ('discord_username', models.CharField(max_length=64)),
                ('discord_global_name', models.CharField(max_length=64)),
                ('discord_avatar', models.CharField(max_length=64)),
                ('osu_user_id', models.BigIntegerField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['discord_user_id', 'osu_user_id'], name='userauth_to_discord_9ba14d_idx')],
            },
        ),
    ]
