# Generated by Django 4.2.6 on 2023-10-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='osu_flag',
            field=models.CharField(default='GB', max_length=4),
            preserve_default=False,
        ),
    ]
