# Generated by Django 4.2.6 on 2023-10-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_tournamentplayer_osu_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
