# Generated by Django 4.2.6 on 2023-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_tournamentplayer_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='osu_username',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
