# Generated by Django 4.2.6 on 2023-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_tournamentplayer_osu_username'),
        ('userauth', '0004_tournamentplayer_userauth_to_osu_use_e7420a_idx'),
    ]

    operations = [
    ]
