# Generated by Django 4.2.6 on 2023-12-03 08:29

from django.db import migrations, models
import django.db.models.deletion
import teammgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('teammgmt', '0001_initial'),
        ('userauth', '0005_merge_20231112_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='team',
            field=models.ForeignKey(default=teammgmt.models.TournamentTeam.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='teammgmt.tournamentteam'),
        ),
    ]
