# Generated by Django 4.2.6 on 2023-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_tournamentplayer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='in_roster',
            field=models.BooleanField(default=False),
        ),
    ]
