# Generated by Django 4.2.6 on 2023-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_tournamentplayer_in_roster'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tournamentplayer',
            index=models.Index(fields=['team'], name='userauth_to_team_id_eaff7d_idx'),
        ),
    ]
