# Generated by Django 4.2.6 on 2023-12-03 11:11

from django.db import migrations, models
import django.db.models.deletion
import teammgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('teammgmt', '0001_initial'),
        ('userauth', '0008_tournamentplayer_userauth_to_team_id_eaff7d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='team',
            field=models.ForeignKey(default=teammgmt.models.TournamentTeam.get_default_pk, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='teammgmt.tournamentteam'),
        ),
    ]
