# Generated by Django 4.2.6 on 2024-01-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_tournamentplayer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='in_backup_roster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='tournamentplayer',
            constraint=models.CheckConstraint(check=models.Q(('in_backup_roster', True), ('in_roster', True), _negated=True), name='not_both_roster_and_backup'),
        ),
    ]
