# Generated by Django 4.2.6 on 2024-01-12 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_tournamentplayer_in_backup_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='osu_rank_std',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='osu_rank_std_bws',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='osu_stats_updated',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0,
                                                                 tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TournamentPlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('award_date', models.DateTimeField()),
                ('url', models.TextField()),
                ('image_url', models.TextField()),
                ('image_url_2x', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.tournamentplayer')),
            ],
        ),
    ]
