# Generated by Django 4.2.6 on 2024-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_tournamentplayer_osu_rank_std_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentplayer',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='tournamentplayerbadge',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
