# Generated by Django 4.2.6 on 2024-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_tournamentplayer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_avatar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='discord_global_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
