# Generated by Django 4.2.6 on 2024-02-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_tournamentplayer_is_captain_and_more'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE userauth_tournamentplayer ALTER COLUMN is_captain DROP DEFAULT;')
    ]
